#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_XIAOMI_FP)     += xiaomi_fp/
obj-$(CONFIG_FINGERPRINT_GOODIX_FOD_G3S)     += goodix_fod_G3S/
